spring:
  datasource:
    driver-class-name: com.sap.db.jdbc.Driver
    url: jdbc:sap://e6f76632-3803-4b0e-a2a7-12c0c527289d.hana.prod-us20.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=P44_DEV_SCHEMA_CKVLR3YFXEPCWVX0TDTEUCK7G_RT
    username: P44_DEV_SCHEMA_CKVLR3YFXEPCWVX0TDTEUCK7G_RT
    password: Co4M7p8-X9dKk39jTfthuuwkN8lOrKZks4hh-DcJ8vPHnxkh3MGbLNvb-O7_JhnYQhLk-teedGnbhO0oxbVHH6X23nF7qweKhS9BLQr_XYUGjMvTuN08KecJPNyj69zj