server:
  port: 8182
  max-http-header-size : 50KB
  connection-timeout: 300000ms
  tomcat:
    relaxed-query-chars: [ '{','}' ]
  #    max-threads: 200
  logging:
    level:
      org:
        springframework:
          security: DEBUG


logging:
  pattern:
    console: "%d [%level] %c{1.} [%t] %m%n"
  level:
    #    org:
    #      hibernate:
    #        SQL: debug
    #        type:
    #          descriptor:
    #            sql: trace
    root: INFO

spring:
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.HANAColumnStoreDialect
    hibernate:
      ddl-auto: update
    #      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        #        format_sql: true
        # default_schema: CM-SCHEMA
  datasource:
    #      driver-class-name: com.sap.db.jdbc.Driver
    #      url: jdbc:sap://zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com:24458?encrypt=true&validateCertificate=true&currentschema=CM-SCHEMA
    #      username: CM-SCHEMA
    #      password: Dr28M0vVSQDmb48YS19-_WISt_6xw7GUM5B4CluWozy7V978NIcgVpAlJDLKt9lyPE81pGI8tG6DiN9ICQImilfS.ssox3J6.vgtLs4C67r8wB3S.xaWTD4hWvKSghz0
    hikari:
      minimumIdle: 10
      maximumPoolSize: 10
      idleTimeout: 120000
      maxLifetime: 500000
  profiles:
    active: dev


