spring:
  datasource:
    driver-class-name: com.sap.db.jdbc.Driver
    url: jdbc:sap://e6f76632-3803-4b0e-a2a7-12c0c527289d.hana.prod-us20.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=P44_DEV_SCHEMA_98QXI4N1NYWML2GCJXJ9KA1YQ_RT
    username: P44_DEV_SCHEMA_98QXI4N1NYWML2GCJXJ9KA1YQ_RT
    password: Qd1YHV8x8NNrkFMU4mpM19bKcx0JsA7s_L.o2kfC74BglcmI38AKWvxNSY-u-lAYCXf5LOfkI81o8vp6jzJhdpuoVaiFayB-H6cU.X6fbw0ZlotzUqcxComi7b.UVvCh

